# Redis配置文件

# 网络设置
bind 0.0.0.0
port 6379
timeout 0
tcp-keepalive 300

# 通用设置
daemonize no
supervised no
pidfile /var/run/redis_6379.pid
loglevel notice
logfile ""
databases 16

# 持久化设置
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data

# 内存设置
maxmemory 512mb
maxmemory-policy allkeys-lru

# 安全设置
requirepass g2rain_redis_11050826

# 客户端设置
maxclients 10000

# 慢日志设置
slowlog-log-slower-than 10000
slowlog-max-len 128

# 延迟监控
latency-monitor-threshold 100
